// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avabuaxnvdjnxadqvfej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2YWJ1YXhudmRqbnhhZHF2ZmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyNjA4NjksImV4cCI6MjA0OTgzNjg2OX0.-wsbR7Pvn88hbm2FgWdCBt5LP2EPzvcqmo7n9URQZ68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);